name: lottery_winner
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  # basic
  flutter_screenutil: ^5.9.1
  flutter_smart_dialog: ^4.9.7+6
  statusbarz: ^1.0.14

  package_info_plus: ^8.0.0
  cached_network_image: ^3.3.1

  # image
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  avatar_stack: ^1.2.0
  flutter_svg: ^2.0.10+1

  # tools
  dropdown_button2: ^2.3.7
  pin_input_text_field: ^4.5.1
  simple_gradient_text: ^1.3.0
  gradient_borders: ^1.0.1
  readmore: ^3.0.0

  # draw
  dotted_line: ^3.2.2
  lottie: ^3.1.2


  # internet
  internet_connection_checker: ^1.0.0+1

  # image_picker
  image_picker: ^1.1.2
  image_cropper: ^7.0.5








dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_gen_runner: ^5.3.2


flutter_gen:
  output: lib/constants/


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/svg/
    - assets/certificate/

  fonts:
    - family: switzer
      fonts:
        - asset: assets/fonts/switzer_black.otf
        - asset: assets/fonts/switzer_bold.otf
        - asset: assets/fonts/switzer_medium.otf
        - asset: assets/fonts/switzer_regular.otf
        - asset: assets/fonts/switzer_semibold.otf

